"""tambah assessment session

Revision ID: 270c6404fdb6
Revises: 5d05a6004ece
Create Date: 2026-03-13 09:08:03.229600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '270c6404fdb6'
down_revision: Union[str, Sequence[str], None] = '5d05a6004ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=5), nullable=False),
    sa.Column('question_ids_served', postgresql.ARRAY(sa.String(length=10)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='assessment_session_status', create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_assessment_sessions_module_id'), 'assessment_sessions', ['module_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_question_ids_served'), 'assessment_sessions', ['question_ids_served'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_user_id'), 'assessment_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_sessions_user_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_question_ids_served'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_module_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    # ### end Alembic commands ###
