"""add thinking time tracking

Revision ID: 494290722d1e
Revises: e7fc5c053600
Create Date: 2026-05-08 12:54:30.190574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494290722d1e'
down_revision: Union[str, Sequence[str], None] = 'e7fc5c053600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_sessions', sa.Column('current_question_start_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('assessment_sessions', 'total_session_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_sessions', 'total_session_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('assessment_sessions', 'current_question_start_time')
    # ### end Alembic commands ###
