"""init migrate

Revision ID: 5d05a6004ece
Revises: 
Create Date: 2026-03-13 06:58:39.362860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d05a6004ece'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('module_id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_min', sa.Float(), nullable=False),
    sa.Column('difficulty_max', sa.Float(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('current_theta', sa.Float(), nullable=False),
    sa.Column('theta_social', sa.Float(), nullable=False),
    sa.Column('k_factor', sa.Integer(), nullable=False),
    sa.Column('has_completed_pretest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_theta >= 0 AND current_theta <= 10000', name='check_current_theta_range'),
    sa.CheckConstraint('k_factor > 0', name='check_k_factor_positive'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_nim'), 'users', ['nim'], unique=True)
    op.create_table('pretest_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('current_theta', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_pretest_sessions_user_id'), 'pretest_sessions', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('module_id', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_query', sa.Text(), nullable=False),
    sa.Column('initial_difficulty', sa.Float(), nullable=False),
    sa.Column('current_difficulty', sa.Float(), nullable=False),
    sa.Column('topic_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_module_id'), 'questions', ['module_id'], unique=False)
    op.create_table('user_module_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=5), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'module_id')
    )
    op.create_table('assessment_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('theta_before', sa.Float(), nullable=False),
    sa.Column('theta_after', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_assessment_logs_question_id'), 'assessment_logs', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_logs_session_id'), 'assessment_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_assessment_logs_timestamp'), 'assessment_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_assessment_logs_user_id'), 'assessment_logs', ['user_id'], unique=False)
    op.create_table('peer_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('review_content', sa.Text(), nullable=False),
    sa.Column('system_score', sa.Float(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_peer_sessions_question_id'), 'peer_sessions', ['question_id'], unique=False)
    op.create_index(op.f('ix_peer_sessions_requester_id'), 'peer_sessions', ['requester_id'], unique=False)
    op.create_index(op.f('ix_peer_sessions_reviewer_id'), 'peer_sessions', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_sessions_reviewer_id'), table_name='peer_sessions')
    op.drop_index(op.f('ix_peer_sessions_requester_id'), table_name='peer_sessions')
    op.drop_index(op.f('ix_peer_sessions_question_id'), table_name='peer_sessions')
    op.drop_table('peer_sessions')
    op.drop_index(op.f('ix_assessment_logs_user_id'), table_name='assessment_logs')
    op.drop_index(op.f('ix_assessment_logs_timestamp'), table_name='assessment_logs')
    op.drop_index(op.f('ix_assessment_logs_session_id'), table_name='assessment_logs')
    op.drop_index(op.f('ix_assessment_logs_question_id'), table_name='assessment_logs')
    op.drop_table('assessment_logs')
    op.drop_table('user_module_progress')
    op.drop_index(op.f('ix_questions_module_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pretest_sessions_user_id'), table_name='pretest_sessions')
    op.drop_table('pretest_sessions')
    op.drop_index(op.f('ix_users_nim'), table_name='users')
    op.drop_table('users')
    op.drop_table('modules')
    # ### end Alembic commands ###
