"""new peer session

Revision ID: 95e87ed14073
Revises: 9c622d1fbc20
Create Date: 2026-03-28 14:24:44.996899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e87ed14073'
down_revision: Union[str, Sequence[str], None] = '9c622d1fbc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_logs', 'stagnation_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('peer_sessions', sa.Column('requester_query', sa.Text(), server_default="", nullable=False))
    op.add_column('peer_sessions', sa.Column('theta_social_before', sa.Float(), nullable=True, server_default=None))
    op.add_column('peer_sessions', sa.Column('theta_social_after', sa.Float(), nullable=True, server_default=None))
    op.add_column('peer_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, server_default=None))
    op.alter_column('users', 'group_assignment',
               existing_type=sa.VARCHAR(length=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'stagnation_ever_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'stagnation_ever_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'group_assignment',
               existing_type=sa.VARCHAR(length=1),
               server_default=sa.text("'B'::character varying"),
               existing_nullable=False)
    op.drop_column('peer_sessions', 'completed_at')
    op.drop_column('peer_sessions', 'theta_social_after')
    op.drop_column('peer_sessions', 'theta_social_before')
    op.drop_column('peer_sessions', 'requester_query')
    op.alter_column('assessment_logs', 'stagnation_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
