"""update ablation study dan safety net

Revision ID: 9c622d1fbc20
Revises: e26b4fafc631
Create Date: 2026-03-28 04:05:05.570615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c622d1fbc20'
down_revision: Union[str, Sequence[str], None] = 'e26b4fafc631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_logs', sa.Column('stagnation_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('group_assignment', sa.String(length=1), server_default=sa.text("'B'"), nullable=False))
    op.add_column('users', sa.Column('stagnation_ever_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stagnation_ever_detected')
    op.drop_column('users', 'group_assignment')
    op.drop_column('assessment_logs', 'stagnation_detected')
    # ### end Alembic commands ###
