"""add is admin

Revision ID: a41f72db17ef
Revises: 95e87ed14073
Create Date: 2026-04-11 04:02:41.930190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41f72db17ef'
down_revision: Union[str, Sequence[str], None] = '95e87ed14073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peer_sessions', 'requester_query',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('peer_sessions', 'requester_query',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    # ### end Alembic commands ###
