"""profile update

Revision ID: e26b4fafc631
Revises: 270c6404fdb6
Create Date: 2026-03-21 07:30:59.813914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26b4fafc631'
down_revision: Union[str, Sequence[str], None] = '270c6404fdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_logs', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('assessment_logs', sa.Column('is_final_attempt', sa.Boolean(), nullable=False))
    op.add_column('assessment_logs', sa.Column('difficulty_before', sa.Float(), nullable=True))
    op.add_column('assessment_logs', sa.Column('difficulty_after', sa.Float(), nullable=True))
    op.alter_column('assessment_logs', 'theta_before',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('assessment_logs', 'theta_after',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('assessment_logs', 'execution_time_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('assessment_sessions', sa.Column('current_question_id', sa.String(length=10), nullable=True))
    op.add_column('assessment_sessions', sa.Column('current_question_attempt_count', sa.Integer(), nullable=False))
    op.add_column('modules', sa.Column('unlock_theta_threshold', sa.Float(), nullable=False))
    op.add_column('modules', sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('user_module_progress', sa.Column('is_unlocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('theta_individu', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('total_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_column('users', 'current_theta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_theta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('users', 'status')
    op.drop_column('users', 'total_attempts')
    op.drop_column('users', 'theta_individu')
    op.drop_column('user_module_progress', 'is_unlocked')
    op.drop_column('modules', 'order_index')
    op.drop_column('modules', 'unlock_theta_threshold')
    op.drop_column('assessment_sessions', 'current_question_attempt_count')
    op.drop_column('assessment_sessions', 'current_question_id')
    op.alter_column('assessment_logs', 'execution_time_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessment_logs', 'theta_after',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('assessment_logs', 'theta_before',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('assessment_logs', 'difficulty_after')
    op.drop_column('assessment_logs', 'difficulty_before')
    op.drop_column('assessment_logs', 'is_final_attempt')
    op.drop_column('assessment_logs', 'attempt_number')
    # ### end Alembic commands ###
