"""add session attempts

Revision ID: e7fc5c053600
Revises: 273a5c0c0156
Create Date: 2026-04-11 09:10:12.450290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fc5c053600'
down_revision: Union[str, Sequence[str], None] = '273a5c0c0156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_sessions', sa.Column('total_session_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('assessment_sessions', 'total_session_attempts')
    # ### end Alembic commands ###
